//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrinkNews
    {
        public int NewsID { get; set; }
        public string Newsimg { get; set; }
        public string NewsName { get; set; }
        public string NewsMesg { get; set; }
        public Nullable<System.DateTime> NewsTime { get; set; }
        public int DrinkID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual DrinkInfo DrinkInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
