//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrinkInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrinkInfo()
        {
            this.DrinkNews = new HashSet<DrinkNews>();
        }
    
        public int DrinkID { get; set; }
        public string Drinkimg { get; set; }
        public string DrinkName { get; set; }
        public string DrinkMesg { get; set; }
        public string Remark { get; set; }
        public int TypeID { get; set; }
    
        public virtual DrinkType DrinkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrinkNews> DrinkNews { get; set; }
    }
}
