//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessInfo
    {
        public int MessID { get; set; }
        public string MessNum { get; set; }
        public string MessName { get; set; }
        public string MessPwd { get; set; }
    }
}
